fix: username at lockscreen
The commit a1b2c01c94796204132360c7c72aa7b1a4b28169 tried to fix an
error: The screen locker widget has been showing the top user name
intead of the username. But this added another error that prints all
user names on the lockscreen. Now, this error has fixed.

---
Changes to be committed:
      modified:   .config/bspwm/screenlocker/widgets/panel.conf